/*
 * ═══════════════════════════════════════════════════════════════
 * Tiny NN Sensor Predictor — ESP32 / Arduino IDE
 * ═══════════════════════════════════════════════════════════════
 *
 * Reads temperature, humidity, pressure, and light (lux) from
 * sensors, feeds them into a tiny neural network, and predicts
 * values ~30 minutes into the future.
 *
 * Network architecture:
 *   Input:  48 (12 timesteps × 4 features)
 *   Hidden: 16 neurons (ReLU)
 *   Hidden:  8 neurons (ReLU)
 *   Output:  4 (temperature, humidity, pressure, lux)
 *
 * Hardware (example — adapt to your sensors):
 *   - BME280 / BME680 for temperature, humidity, pressure (I2C)
 *   - BH1750 for lux (I2C)
 *
 * After training, copy nn_weights.h into the same folder as
 * this .ino file.
 * ═══════════════════════════════════════════════════════════════
 */

#include "nn_weights.h"   // auto-generated by train_model.py

// ─── Sensor includes (uncomment / swap for your hardware) ────
// #include <Wire.h>
// #include <Adafruit_BME280.h>
// #include <BH1750.h>
// Adafruit_BME280 bme;
// BH1750 lightMeter;

// ─── Ring buffer for lookback window ─────────────────────────
// Stores the last NN_LOOKBACK readings (each has 4 features)
float sensorBuffer[NN_LOOKBACK][4];
int   bufferIndex  = 0;
int   bufferCount  = 0;

// ─── Timing ──────────────────────────────────────────────────
// Match the training sampling interval (5 seconds)
const unsigned long SAMPLE_INTERVAL_MS = 5000;
unsigned long lastSampleTime = 0;

// ─── NN inference buffers ────────────────────────────────────
float inputVec[NN_INPUT_DIM];
float hidden1[NN_HIDDEN1];
float hidden2[NN_HIDDEN2];
float output[NN_OUTPUT_DIM];

// ═════════════════════════════════════════════════════════════
//  Helper: read a PROGMEM float array into a local float
// ═════════════════════════════════════════════════════════════
static inline float pgm_read_float_near(const float* addr) {
    float val;
    memcpy_P(&val, addr, sizeof(float));
    return val;
}

// ═════════════════════════════════════════════════════════════
//  ReLU activation
// ═════════════════════════════════════════════════════════════
static inline float relu(float x) {
    return x > 0.0f ? x : 0.0f;
}

// ═════════════════════════════════════════════════════════════
//  Sigmoid activation
// ═════════════════════════════════════════════════════════════
static inline float sigmoid(float x) {
    return 1.0f / (1.0f + expf(-x));
}

// ═════════════════════════════════════════════════════════════
//  Dense layer forward pass (weights in PROGMEM)
// ═════════════════════════════════════════════════════════════
void denseForward(
    const float* input,  int inSize,
    float* output,       int outSize,
    const float* weights,       // PROGMEM, shape [inSize * outSize] (row-major)
    const float* biases,        // PROGMEM, shape [outSize]
    char activation             // 'r' = ReLU, 's' = sigmoid, 'n' = none
) {
    for (int j = 0; j < outSize; j++) {
        float sum = pgm_read_float_near(&biases[j]);
        for (int i = 0; i < inSize; i++) {
            float w = pgm_read_float_near(&weights[i * outSize + j]);
            sum += input[i] * w;
        }
        if (activation == 'r')      sum = relu(sum);
        else if (activation == 's')  sum = sigmoid(sum);
        output[j] = sum;
    }
}

// ═════════════════════════════════════════════════════════════
//  Full NN inference
// ═════════════════════════════════════════════════════════════
void nnPredict(float* inputVec, float* result) {
    // Layer 1: input(48) -> hidden1(16), ReLU
    denseForward(inputVec, NN_INPUT_DIM, hidden1, NN_HIDDEN1,
                 W_HIDDEN1, B_HIDDEN1, 'r');

    // Layer 2: hidden1(16) -> hidden2(8), ReLU
    denseForward(hidden1, NN_HIDDEN1, hidden2, NN_HIDDEN2,
                 W_HIDDEN2, B_HIDDEN2, 'r');

    // Layer 3: hidden2(8) -> output(4), Sigmoid
    denseForward(hidden2, NN_HIDDEN2, result, NN_OUTPUT_DIM,
                 W_OUTPUT, B_OUTPUT, 's');
}

// ═════════════════════════════════════════════════════════════
//  Normalize a raw sensor reading
// ═════════════════════════════════════════════════════════════
float normalize(float raw, int featureIdx) {
    float mn  = pgm_read_float_near(&FEAT_MIN[featureIdx]);
    float rng = pgm_read_float_near(&FEAT_RANGE[featureIdx]);
    return (raw - mn) / rng;
}

// ═════════════════════════════════════════════════════════════
//  Denormalize a predicted value back to real units
// ═════════════════════════════════════════════════════════════
float denormalize(float norm, int featureIdx) {
    float mn  = pgm_read_float_near(&FEAT_MIN[featureIdx]);
    float rng = pgm_read_float_near(&FEAT_RANGE[featureIdx]);
    return norm * rng + mn;
}

// ═════════════════════════════════════════════════════════════
//  Read sensors (REPLACE with your actual sensor code)
// ═════════════════════════════════════════════════════════════
void readSensors(float* temperature, float* humidity, float* pressure, float* lux) {
    // ── Replace this block with real sensor reads ──
    // *temperature = bme.readTemperature();
    // *humidity    = bme.readHumidity();
    // *pressure    = bme.readPressure();  // Pa
    // *lux         = lightMeter.readLightLevel();

    // Placeholder: generate dummy data for testing
    *temperature = 24.0 + random(-10, 10) * 0.1;
    *humidity    = 34.0 + random(-20, 20) * 0.1;
    *pressure    = 98489.0 + random(-50, 50);
    *lux         = 15.0 + random(0, 20);
}

// ═════════════════════════════════════════════════════════════
//  SETUP
// ═════════════════════════════════════════════════════════════
void setup() {
    Serial.begin(115200);
    delay(1000);

    Serial.println();
    Serial.println("══════════════════════════════════════════");
    Serial.println("  Tiny NN Sensor Predictor — ESP32");
    Serial.println("══════════════════════════════════════════");
    Serial.printf("  Input dim:  %d (%d steps × 4 features)\n", NN_INPUT_DIM, NN_LOOKBACK);
    Serial.printf("  Hidden1:    %d neurons\n", NN_HIDDEN1);
    Serial.printf("  Hidden2:    %d neurons\n", NN_HIDDEN2);
    Serial.printf("  Output:     %d values\n", NN_OUTPUT_DIM);
    Serial.println("══════════════════════════════════════════");

    // ── Initialize sensors (uncomment for real hardware) ──
    // Wire.begin();
    // if (!bme.begin(0x76)) {
    //     Serial.println("BME280 not found!");
    //     while (1) delay(10);
    // }
    // if (!lightMeter.begin()) {
    //     Serial.println("BH1750 not found!");
    //     while (1) delay(10);
    // }

    Serial.println("Filling buffer... (need 12 readings)");
    Serial.println();
}

// ═════════════════════════════════════════════════════════════
//  LOOP
// ═════════════════════════════════════════════════════════════
void loop() {
    unsigned long now = millis();
    if (now - lastSampleTime < SAMPLE_INTERVAL_MS) return;
    lastSampleTime = now;

    // 1. Read sensors
    float temp, hum, pres, lx;
    readSensors(&temp, &hum, &pres, &lx);

    // 2. Normalize and store in ring buffer
    sensorBuffer[bufferIndex][0] = normalize(temp, 0);
    sensorBuffer[bufferIndex][1] = normalize(hum,  1);
    sensorBuffer[bufferIndex][2] = normalize(pres, 2);
    sensorBuffer[bufferIndex][3] = normalize(lx,   3);
    bufferIndex = (bufferIndex + 1) % NN_LOOKBACK;
    if (bufferCount < NN_LOOKBACK) bufferCount++;

    // Print current reading
    Serial.printf("NOW  → T:%.1f°C  H:%.1f%%  P:%.0fPa  L:%.1flux\n",
                  temp, hum, pres, lx);

    // 3. Run inference once buffer is full
    if (bufferCount >= NN_LOOKBACK) {
        // Flatten ring buffer into input vector (oldest first)
        int start = bufferIndex;  // oldest entry in ring buffer
        for (int s = 0; s < NN_LOOKBACK; s++) {
            int idx = (start + s) % NN_LOOKBACK;
            for (int f = 0; f < 4; f++) {
                inputVec[s * 4 + f] = sensorBuffer[idx][f];
            }
        }

        // Run NN
        nnPredict(inputVec, output);

        // Denormalize predictions
        float predTemp  = denormalize(output[0], 0);
        float predHum   = denormalize(output[1], 1);
        float predPres  = denormalize(output[2], 2);
        float predLux   = denormalize(output[3], 3);

        Serial.printf("PRED → T:%.1f°C  H:%.1f%%  P:%.0fPa  L:%.1flux  (in ~30 min)\n",
                      predTemp, predHum, predPres, predLux);
    } else {
        Serial.printf("Buffer: %d/%d readings\n", bufferCount, NN_LOOKBACK);
    }

    Serial.println();
}
